import LoginBgImage from '../Icons/bg-image.jpg'
import insearchFor from '../Icons/InsearchForIcon.svg'
import coveringGeoLocation from '../Icons/coveringGeoLocation.svg'
import carbonEnergy from '../Icons/carbonenergyrenewable.svg'
import LeafIcon from '../Icons/LeafIcon.svg'
import rideBookLogo from '../Icons/ride-book-logo.svg'
import driveGrin from '../Icons/drive-grin.svg'
import weeklyPayouts from '../Icons/weeklyPayouts.svg'
import flexibleHours from '../Icons/flexibleHours.svg'
import zeroOwnerShip from '../Icons/zeroOwner.svg'
import GrinLogo from '../Icons/Grin-Logo.png'
import footerLogo from '../Icons/Grin-Logo.png'
import RideWithUsImgae from '../Icons/ride-with-us-image.svg'
import sourceIcon from '../Icons/source-icon.svg'
import whereToIcon from '../Icons/whereToIcon.svg'
import economyCar from '../Icons/economy-car.jpg'
import comfortCar from '../Icons/comfort-car.jpg'
import bookAride from '../Icons/bookaride.svg'


export{LoginBgImage,bookAride,comfortCar,economyCar,insearchFor,whereToIcon,sourceIcon,coveringGeoLocation,carbonEnergy,LeafIcon,rideBookLogo,driveGrin,weeklyPayouts,flexibleHours,zeroOwnerShip,GrinLogo,footerLogo,RideWithUsImgae}